"""add_user_preferences

Revision ID: 7f8ff49b838b
Revises: 3bcd0ec173d6
Create Date: 2025-11-26 21:26:06.013280
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f8ff49b838b'
down_revision: Union[str, None] = '3bcd0ec173d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns with server defaults for existing rows
    op.add_column('users', sa.Column('preferred_ai_provider', sa.String(length=20), nullable=False, server_default='claude'))
    op.add_column('users', sa.Column('timezone', sa.String(length=50), nullable=False, server_default='Europe/Stockholm'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'timezone')
    op.drop_column('users', 'preferred_ai_provider')
    # ### end Alembic commands ###
